### ISSUE TITLE
Seeing nil jobs show up from time to time

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx-dashboard#27]
{:tasks {}, :workflow nil, :status :finished, :catalog nil} 

These, of course, display with an age of 45 years.

**Comment by johnohara89** [comment]
I experience this when I submit a kill-job that doesn't actually kill the currently executing job.

I am attempting to kill the job using a separate kill-job namespace which calls onyx.api/kill-job with peer-config and job-id.

```
java -jar target/test-0.1.0-SNAPSHOT-standalone.jar -m test.launcher.kill-prod-sample-job my-test 08b44bdf-deef-4b35-ab7e-d65b705e691c
```
This is the main for my kill-job namespace:
```clojure
(defn -main [onyx-id job-id]
      (let [cfg (-> "env-config.edn" resource slurp read-string)
            peer-config (assoc cfg :onyx/id onyx-id)]
           (onyx.api/kill-job peer-config job-id)))
```

**Comment by MichaelDrogalis** [comment]
@johnohara89 Thanks! I'll try to take a look at this one this weekend.

**Comment by johnohara89** [comment]
The mistake I was making was passing in the job-id as a string instead of a UUID.

**Comment by MichaelDrogalis** [comment]
We should make a change in core and always cast what the user gives us to a string to avoid this, since both a string and UUID are valid job IDs at the moment.

**Comment by lbradstreet** [comment]
Fixed in https://github.com/onyx-platform/onyx/commit/24cd4f3fd4073e5767a39bf5d24bbf20d3e4680f
