### ISSUE TITLE
New build lacks httpcore

### ISSUE THREAD

**Issue by gardnervickers** [onyx-platform/onyx-dashboard#35]
When I lein-figwheel for the first time, I get a message saying I am lacking the httpcore jar. 

```
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpcore</artifactId>
    <version>4.4</version>
</dependency>

```

Fixed it.

**Comment by lbradstreet** [comment]
Thanks, that helps a lot. I had removed figwheel in master. I'll see if bumping the figwheel version helps - I'm not quite sure why we need the extra dep.

**Comment by gardnervickers** [comment]
Its totally broken for me right now. Figwheel builds but wont connect to my browser. I'll take a whack at.

**Comment by lbradstreet** [comment]
Yep, fair enough. I've been using cljsbuild alone to dev with for quite a while.

**Comment by gardnervickers** [comment]
Was no longer seeing this issue
