### ISSUE TITLE
dashboard shows nothing.

### ISSUE THREAD

**Issue by yusupp** [onyx-platform/onyx-dashboard#40]
Hi,

Here is my setup and problem.

Here is peer-config for  dashboard. ZK is a standalone instance.
ZK and onyx-dashboard are on the same machine.

```
{:zookeeper/address "10.240.0.4:2188"
 :onyx.peer/job-scheduler :onyx.job-scheduler/greedy
 :onyx.messaging/impl :aeron
 :onyx.messaging/peer-port 40200
 :onyx.messaging/bind-addr "10.240.0.4"}
```

Here are peer-config,env-config for each peers, bind-addr is  assoced after loading peer config.
```
{:zookeeper/address "10.240.0.4:2181"
 :onyx.peer/job-scheduler :onyx.job-scheduler/greedy
 :onyx.messaging/impl :aeron
; :onyx.messaging/bind-addr "localhost"
 :onyx.messaging/peer-port 40200
 :onyx.messaging.aeron/embedded-driver? true}
 ```
 
```
{:zookeeper/address "10.240.0.4:2181"
 :zookeeper/server? false
 :zookeeper.server/port 2181}
```

BTW, port is already in the address why another port option for ZK ? 

I have two nodes , and I can not see anything while I run a job which is executed by each nodes(I can see println results from each.).

I've got error from firefox console,  and here is link for [screenshot](http://imgur.com/bItE2QY)

```
First opened:  [:chsk/state {:type :ws, :open? true, :destroyed? false, :uid c1c5bfd7-5574-4031-884b-47b89918e47e, :csrf-token acNAA8zBguSssLA7NDF3S5h2SxnrJJKMyh3bfS+mTbtHIYQgmL++r1bbXq+O1/SLVs77ZyLnRZsYMR8L, :first-open? true}] core.js:100:1
ERROR: Chsk router handling error ([:chsk/handshake ["c1c5bfd7-5574-4031-884b-47b89918e47e" "acNAA8zBguSssLA7NDF3S5h2SxnrJJKMyh3bfS+mTbtHIYQgmL++r1bbXq+O1/SLVs77ZyLnRZsYMR8L"]]): Error: No matching clause: :chsk/handshake encore.js:3832:8
Figwheel: trying to open cljs reload socket utils.js:86:8
Figwheel: socket connection established utils.js:86:8
```

Thanks

**Comment by lbradstreet** [comment]
Hi @usupa,

It looks like you're using onyx-0.8.0-alpha1, however you are probably not using the corresponding onyx-dashboard version, as we haven't put one up in the releases dir.

Can you try out this release and let me know how you go?

https://circle-artifacts.com/gh/onyx-platform/onyx-dashboard/244/artifacts/0/tmp/circle-artifacts.dJfYBAc/onyx-dashboard.jar

**Comment by yusupp** [comment]
After running the jar , the same result . 
I checked out the lastest onyx-dashboard version, which is labeled 0.8.x .

**Comment by lbradstreet** [comment]
Ohhhh, you're using port 2188 for the dashboard and 2181 for the other instance. I might change that port in the code because that's an easy mistake to make.

**Comment by yusupp** [comment]
my bad :( , silly mistake. thanks

**Comment by yusupp** [comment]
all good after port update. looks great.
