### ISSUE TITLE
Selenium issues

### ISSUE THREAD

**Issue by bsima** [onyx-platform/onyx-dashboard#41]
Sometimes, the proper Selenium dependencies aren't pulled in with clj-webdriver. Details:

* I was getting [this stack trace](https://gist.github.com/bsima/7477addb027d442b4814#file-onyx-dashboard-err-txt).
* and [these deps](https://gist.github.com/bsima/7477addb027d442b4814#file-deps-txt).

Fixed by adding some dev dependencies, as per [this comment](https://github.com/semperos/clj-webdriver/issues/127#issuecomment-52914747). The patch is small:

```patch
modified   project.clj
@@ -75,6 +75,9 @@
 
                    :dependencies [[figwheel "0.3.3"]
                                   [clj-webdriver "0.6.1"]
+                                  [org.apache.httpcomponents/httpcore "4.3"]
+                                  [org.apache.httpcomponents/httpclient "4.3"]
+                                  [org.apache.httpcomponents/httpmime "4.3"]
                                   ;[com.cemerick/piggieback "0.2.1"]
                                   ;[weasel "0.5.0"]
                                   [leiningen "2.5.1"]]
```

If this becomes a regular issue, then it might be prudent to add those dependencies, but I'm not sure if this would cause other issues. Namely, this issue might be dependent on the user's local environment, see [this comment](https://github.com/semperos/clj-webdriver/issues/127#issuecomment-52920432). So, I'll just leave this here as research :)

Other relevant issues:

- [luminus-template #126](https://github.com/luminus-framework/luminus-template/issues/126)
- [clj-webdriver #107](https://github.com/semperos/clj-webdriver/issues/107)
- [clj-webdriver #127](https://github.com/semperos/clj-webdriver/issues/127)

**Comment by lbradstreet** [comment]
Works for me after adding httpcore. Not sure why it needs it but I'll hack around it for now.
