### ISSUE TITLE
Config through environ

### ISSUE THREAD

**Issue by gardnervickers** [onyx-platform/onyx-dashboard#43]
In order to support docker and the links facility of docker-compose, we should use [environ](https://github.com/weavejester/environ). Feel free to reject this, I can work around it with the template.

We can use a .lein-env file to replace the config file normally used.

**Comment by MichaelDrogalis** [comment]
:+1:

**Comment by gardnervickers** [comment]
I am actually just going to drop the peer-config file format totally if that's fine, seeing as all we use from it is `:zookeeper/address`

**Comment by gardnervickers** [comment]
On second thought, just changing the default for `:zookeeper/address` from `127.0.0.1:2188` to `zk:2188`  is less intrusive and allows for sharing peer-configs, something I quite like.
