### ISSUE TITLE
Dashboard uberjars

### ISSUE THREAD

**Issue by vsolovyov** [onyx-platform/onyx-dashboard#44]
Would be cool to have up-to-date onyx-dashboard uberjar for the last version.

**Comment by lbradstreet** [comment]
Yeah, we've slacked off a bit here, because we haven't automated the release process to release to github releases. Our apologies. We'll try to sort this out some time soon.

**Comment by dignati** [comment]
Agreed, this would be good to have. In the mean time you can figure out the link to the cirlceci artifact yourself. This is the latest artifact for onyx 0.8.8: https://circle-artifacts.com/gh/onyx-platform/onyx-dashboard/382/artifacts/0/tmp/circle-artifacts.Erk853h/onyx-dashboard.jar

**Comment by lbradstreet** [comment]
This was solved a while back. You can find all the releases here:

https://github.com/onyx-platform/onyx-dashboard/blob/master/RELEASES.md
