### ISSUE TITLE
Task graph is too big for canvas when too many tasks are in the workflow

### ISSUE THREAD

**Issue by aengelberg** [onyx-platform/onyx-dashboard#58]
![image](https://cloud.githubusercontent.com/assets/4122172/18096728/1375ca02-6e90-11e6-9d41-ea77f19de811.png)

Happy to provide more detail on my issue if this is not enough of a description and repro case.

**Comment by mariusz-jachimowicz-83** [comment]
Very long names.

**Comment by mariusz-jachimowicz-83** [comment]
should be resolved via https://github.com/lbradstreet/onyx-visualization/pull/4 by adding zooming

**Comment by lbradstreet** [comment]
Fixed in master. Thanks @mariusz-jachimowicz-83!
