### ISSUE TITLE
Display logging messages from included jars

### ISSUE THREAD

**Issue by mariusz-jachimowicz-83** [onyx-platform/onyx-dashboard#65]
Add dependencies that allows to log messages from included jars. It is usefull to see this messages for debbuging.
- [x] fix  `Bad server ev-msg` message in console when `com.fzakaria/slf4j-timbre` dep is used. The same problem exists in sente example project. Problem not exists when `com.fzakaria/slf4j-timbre` is commented.

**Comment by mariusz-jachimowicz-83** [comment]
I have added comment in related PR from Sente - https://github.com/ptaoussanis/sente/issues/266

**Comment by lbradstreet** [comment]
Reviewing this one now. One thought is that it might be a good idea to just put the timbre dependencies in the dev map so we can use them during dev without enabling.

**Comment by lbradstreet** [comment]
I was about to close this one, but just realised that I might have made a mistake including slf4j-timbre if it causes additional sente problems. Is it possible that it's just exposing an existing problem?
