### ISSUE TITLE
dashboard wont show information: code: -101     path: "/onyx/1/log-parameters/log-parameters"

### ISSUE THREAD

**Issue by drewverlee** [onyx-platform/onyx-dashboard#69]
onyx version:

```
  :dependencies [[aero "1.0.0-beta2"]
                 [org.clojure/clojure "1.8.0"]
                 [org.clojure/tools.cli "0.3.5"]
                 [org.onyxplatform/onyx "0.9.10"]
                 [org.onyxplatform/lib-onyx "0.9.10.0"]]
```

 lein new onyx-app my-app-name -- +docker
  lein do clean, uberjar; docker build -t peerimage .

➜  my-app-name git:(master) ✗ docker-compose run --entrypoint=java peer "-cp" "opt/peer.jar" "res.core" "start-peers" "3"
Starting peer-group
Starting env
Starting peers
Attempting to connect to Zookeeper @ 127.0.0.1:2188
Started peers. Blocking forever.

➜  my-app-name git:(master) ✗ docker-compose run --entrypoint=java peer "-cp" "opt/peer.jar" "res.core" "submit-job" "basic-job" "-p" ":docker"
16-Oct-11 02:25:59 e205fac32abc INFO [onyx.log.zookeeper] - Starting ZooKeeper client connection. If Onyx hangs here it may indicate a difficulty connecting to ZooKeeper.
16-Oct-11 02:26:00 e205fac32abc INFO [onyx.log.zookeeper] - Stopping ZooKeeper client connection
Successfully submitted job:  #uuid "2af060f8-ac24-4a2d-9cfe-fd97490090b6"
Blocking on job completion...
16-Oct-11 02:26:00 e205fac32abc INFO [onyx.log.zookeeper] - Starting ZooKeeper client connection. If Onyx hangs here it may indicate a difficulty connecting to ZooKeeper.
16-Oct-11 02:26:00 e205fac32abc INFO [onyx.log.zookeeper] - Starting ZooKeeper client connection. If Onyx hangs here it may indicate a difficulty connecting to ZooKeeper.

➜  my-app-name git:(master) ✗ docker run -p 3000:3000 onyx/onyx-dashboard:latest "172.17.0.2:2181"
Starting Sente
Starting HTTP Server
Http-kit server is running at http://localhost:3000/

refresh localhost page

➜  my-app-name git:(master) ✗ docker run -p 3000:3000 onyx/onyx-dashboard:latest "172.17.0.2:2181"
Starting Sente
Starting HTTP Server
Http-kit server is running at http://localhost:3000/
Connected:  192.168.99.1 9056876e-caca-4e6a-83d1-961d47cc9855

select id on dashboad

➜  my-app-name git:(master) ✗ docker run -p 3000:3000 onyx/onyx-dashboard:latest "172.17.0.2:2181"
Starting Sente
Starting HTTP Server
Http-kit server is running at http://localhost:3000/
Connected:  192.168.99.1 8c8d697c-1aef-47c8-83b7-49d76903986c
16-10-11 02:34:31 0d3b8c8d4754 INFO [onyx-dashboard.tenancy:103] - Starting Track Tenancy manager for tenancy  1 {:zookeeper/address "172.17.0.2:2181", :onyx.peer/job-scheduler :not-required/for-peer-sub, :onyx.messaging/impl :aeron, :onyx.messaging/bind-addr "localhost", :onyx/tenancy-id "1"} 8c8d697c-1aef-47c8-83b7-49d76903986c
16-10-11 02:34:31 0d3b8c8d4754 INFO [onyx.log.zookeeper:97] - Starting ZooKeeper client connection. If Onyx hangs here it may indicate a difficulty connecting to ZooKeeper.
16-10-11 02:34:31 0d3b8c8d4754 WARN [onyx.log.zookeeper:206] -
                                                 java.lang.Thread.run              Thread.java:  745
                   java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  617
                    java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1142
                                                                  ...
                                    clojure.core.async/thread-call/fn                async.clj:  434
                                             onyx.log.zookeeper/fn/fn            zookeeper.clj:  235
                               onyx.log.zookeeper/find-log-parameters            zookeeper.clj:  203
                            onyx.log.zookeeper/find-log-parameters/fn            zookeeper.clj:  204
                                                                  ...
                                                onyx.log.zookeeper/fn            zookeeper.clj:  548
                                                onyx.log.zookeeper/fn            zookeeper.clj:  550
                         onyx.monitoring.measurements/measure-latency         measurements.clj:   11
                                             onyx.log.zookeeper/fn/fn            zookeeper.clj:  551
                       onyx.log.zookeeper/clean-up-broken-connections            zookeeper.clj:   77
                                          onyx.log.zookeeper/fn/fn/fn            zookeeper.clj:  554
                                                onyx.log.curator/data              curator.clj:  126
       org.apache.curator.framework.imps.GetDataBuilderImpl$2.forPath  GetDataBuilderImpl.java:  138
       org.apache.curator.framework.imps.GetDataBuilderImpl$2.forPath  GetDataBuilderImpl.java:  142
         org.apache.curator.framework.imps.GetDataBuilderImpl.forPath  GetDataBuilderImpl.java:  279
org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground  GetDataBuilderImpl.java:  287
                           org.apache.curator.RetryLoop.callWithRetry           RetryLoop.java:  107
          org.apache.curator.framework.imps.GetDataBuilderImpl$4.call  GetDataBuilderImpl.java:  291
          org.apache.curator.framework.imps.GetDataBuilderImpl$4.call  GetDataBuilderImpl.java:  302
                               org.apache.zookeeper.ZooKeeper.getData           ZooKeeper.java: 1155
                          org.apache.zookeeper.KeeperException.create     KeeperException.java:   51
                          org.apache.zookeeper.KeeperException.create     KeeperException.java:  111
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /onyx/1/log-parameters/log-parameters
    code: -101
    path: "/onyx/1/log-parameters/log-parameters"

16-10-11 02:34:31 0d3b8c8d4754 WARN [onyx.log.zookeeper:207] - Log parameters couldn't be discovered. Backing off 500ms and trying again...
16-10-11 02:34:32 0d3b8c8d4754 WARN [onyx.log.zookeeper:206] -

and the dashboard : https://www.dropbox.com/s/7t3wmvgw4e2bfw6/Screenshot%202016-10-11%2009.08.56.png?dl=0

**Comment by MichaelDrogalis** [comment]
@drewverlee Does it eventually work? This warning is emitted when basic data needed to start reading the log can't be found, and spins until it finds it. If the dashboard is started before the cluster you'd see this message.

Otherwise, are you sure you the dashboard is pointing at the right tenancy ID?

**Comment by drewverlee** [comment]
@MichaelDrogalis Everything works if i use the same version of onyx as the dashboard.
