### ISSUE TITLE
Bring Kill Job Back

### ISSUE THREAD

**Issue by alexanderkiel** [onyx-platform/onyx-dashboard#72]
In version 0.9.12.0, the kill job function is not available anymore. @lbradstreet said, it was removed in a refactoring. It would be nice to have it back. I would use it to quickly kill jobs wich have a problem.

I could kill jobs from inside a REPL but it takes longer and could be even harder for my colleagues.

**Comment by mariusz-jachimowicz-83** [comment]
@alexanderkiel it could be closed if my PR works well, right? It is available on master branch now.

**Comment by MichaelDrogalis** [comment]
Thanks. Yes, closing.
